maremma

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -71,4 +71,31 @@ echo "tested!!!!"
 
 # HERE STARTS THE SECOND ONE
 
+set -e # bail if any command fails
 
+MAXMINDDB_VERSION=${MAXMINDDB_VERSION-1.1.0}
+apxs_path=${APXS_PATH-/app/.heroku/php/bin/apxs}
+
+maxminddb_tarball_url=https://github.com/maxmind/mod_maxminddb/releases/download/${MAXMINDDB_VERSION}/mod_maxminddb-${MAXMINDDB_VERSION}.tar.gz
+
+temp_dir=$(mktemp -d /tmp/maxmind.XXXXXXXXXX)
+
+cleanup() {
+  echo "Cleaning up $temp_dir"
+  echo "DIOCAN"
+  cd /
+  rm -rf "$temp_dir"
+}
+trap cleanup EXIT
+cd $temp_dir
+echo "Temp dir: $temp_dir"
+echo "Downloading $maxminddb_tarball_url"
+curl -o mod_maxminddb-${MAXMINDDB_VERSION}.tar.gz -L $maxminddb_tarball_url
+tar -zxvf mod_maxminddb-${MAXMINDDB_VERSION}.tar.gz
+(
+    cd mod_maxminddb-${MAXMINDDB_VERSION}
+    ./configure -h
+  ./configure --with-apxs=${APXS_PATH} --libdir=/app/tmp/cache/libmaxminddb/lib
+  make install
+)
+trap cleanup EXIT
